apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq3
  namespace: mq
  labels: 
    testTarget: mq2
spec:
  license:
    accept: true
    license: L-YBXJ-ADJNSM
   # license: L-RJON-BN7PN3
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    imagePullPolicy: Always
    storage:
      defaultClass: imbc-vpc-block-10iops-tier
      queueManager:
        type: persistent-claim
        size: 10Gi
    resources:
      limits:
        cpu: '0.5'
        memory: 2Gi
      requests:
        cpu: '0.5'
        memory: 2Gi
    availability:
      updateStrategy: RollingUpdate
      type: SingleInstance
   #   type: NativeHA
    name: QM1
    mqsc:
    - configMap:
        name: mq2-mqsc
        items:
        - ivt.mqsc
    ini:
    - configMap:
        name: mq2-mqsc
        items:
        - mq.ini
  #template:
  #  pod:
  #    containers:
  #      - env:
  #          - name: MQSNOAUT
  #            value: 'yes'
  #        name: qmgr
  version: 9.3.3.0-r1
  web:
    enabled: false
  pki:
    keys:
      - name: qmlabel
        secret:
          secretName: mq2key
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust1
        secret:
          secretName: tls-trust
          items:
            - tls.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
