apiVersion: v1
kind: ConfigMap
metadata:
  name: mq2-mqsc
data:
  ivt.mqsc: |
    DEFINE CHANNEL(TLS2) CHLTYPE(SVRCONN) SSLCIPH(TLS_RSA_WITH_AES_128_CBC_SHA256) CERTLABL('qmlabel') SSLCAUTH (OPTIONAL) REPLACE
    SET CHLAUTH(TLS2) TYPE(BLOCKUSER) USERLIST(nobody)
    SET CHLAUTH(TLS2) TYPE (ADDRESSMAP) ADDRESS(*) MCAUSER('user1')
    DEFINE CHANNEL(ACE.CONN) CHLTYPE(SVRCONN) REPLACE
    SET CHLAUTH(ACE.CONN) TYPE(BLOCKUSER) USERLIST(nobody)
    SET CHLAUTH(ACE.CONN) TYPE (ADDRESSMAP) ADDRESS(*) MCAUSER('user1')
    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(NONE) ADOPTCTX(NO)
    SET AUTHREC PRINCIPAL('user1') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE('IVT.Q') PRINCIPAL('user1') OBJTYPE(QUEUE) AUTHADD(BROWSE,CHG,CLR,DLT,DSP,GET,INQ,PUT,PASSALL,PASSID,SET,SETALL,SETID)
    SET AUTHREC PROFILE('IVT.P') PRINCIPAL('user1') OBJTYPE(QUEUE) AUTHADD(BROWSE,CHG,CLR,DLT,DSP,GET,INQ,PUT,PASSALL,PASSID,SET,SETALL,SETID)
    REFRESH SECURITY TYPE(CONNAUTH)
    DEFINE QLOCAL(IVT.Q) DEFPSIST(YES) MAXDEPTH(5000000) REPLACE
    DEFINE QLOCAL(IVT.R) DEFPSIST(YES) MAXDEPTH(5000000) REPLACE
    DEFINE QLOCAL(IVT.P) DEFPSIST(YES) MAXDEPTH(5000000) REPLACE
    DEFINE QLOCAL(BACKEND.QUEUE) DEFPSIST(YES) MAXDEPTH(5000000) REPLACE
  mq.ini: |-
    Service:
      Name=AuthorizationService
      EntryPoints=14
      SecurityPolicy=UserExternal
